services:
  postgres:
    image: postgres:14
    container_name: ho-sp-db-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ho-sp-db-sc-notification
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  activemq:
    image: rmohr/activemq:5.15.9
    container_name: ho-sp-broker-activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: ho-sp-broker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT)PASS: guest


  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: ho-sp-broker-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: ho-sp-broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  redis:
    image: redis:7-alpine
    container_name: ho-sp-cache-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: